version: '3'

services:
  arango:
    image: arangodb:3.10
    container_name: arango
    restart: always
    environment:
      ARANGO_NO_AUTH: '1'
    ports:
      - 8529:8529
    volumes:
      - arango-data:/var/lib/arangodb3/
  moodlenet:
    image: ponlawatw/moodlenet:3.2.0
    container_name: moodlenet
    restart: always
    ports:
      - 8080:8080
    volumes:
      - moodlenet-data:/app/fs/
      - ./default.config.json:/app/default.config.json
      - ./default.crypto.privateKey:/app/default.crypto.privateKey
      - ./default.crypto.publicKey:/app/default.crypto.publicKey

volumes:
  arango-data: {}
  moodlenet-data: {}
